### ISSUE TITLE
Package depends on R 3.50

### ISSUE THREAD

**Issue by marohrdanz** [MD-Anderson-Bioinformatics/rppaspace#1]
The R package doesn't build under R 3.6.* because the Depends line in DESCRIPTION sepcifies R version 3.50. Maybe the intent was '3.5.0'?

**Comment by jmelott** [comment]
Please download package code again (v1.0.7) and try again.   I'm surprised CRAN didn't detect that in their tests if it is an issue.  Maybe that's coming with the next set of problems?

**Comment by marohrdanz** [comment]
That works! Thanks for the quick turn around!
